<?php
define('ROOT_PATH',dirname(__DIR__) . DIRECTORY_SEPARATOR);
define('APP_PATH', ROOT_PATH  . 'src' .  DIRECTORY_SEPARATOR);
define('CONFIG_PATH', ROOT_PATH . 'config' .  DIRECTORY_SEPARATOR);
define('TMP_PATH', ROOT_PATH  . 'tmp' .  DIRECTORY_SEPARATOR);
define('WEB_PATH', ROOT_PATH  . 'web' .  DIRECTORY_SEPARATOR);
define('CACHE_PATH', TMP_PATH  . 'cache' . DIRECTORY_SEPARATOR);
define('LOG_PATH', TMP_PATH  . 'logs' . DIRECTORY_SEPARATOR);

define('RESOURCE_PATH', ROOT_PATH  . 'src' . DIRECTORY_SEPARATOR . 'Resource' . DIRECTORY_SEPARATOR);
define('THEME_PATH', RESOURCE_PATH . 'themes' .  DIRECTORY_SEPARATOR);
define('VIEW_PATH', RESOURCE_PATH . 'view' .  DIRECTORY_SEPARATOR);
define('ASSET_PATH', RESOURCE_PATH . 'assets' .  DIRECTORY_SEPARATOR);