# see http://about.travis-ci.org/docs/user/languages/php/ for more hints
language: php

php:
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install

script: phpunit --configuration phpunit.xml --coverage-text

notifications:
  email: false